services:
  dashboard_analyzer:
    build: .
    env_file: .env
    platform: linux/amd64
    ports:
      - "9000:8080"
    entrypoint:
      - /usr/local/bin/aws-lambda-rie
    environment:
      - DYNAMODB_TABLE_NAME=dashboard_analyzer_param_table
      - DYNAMODB_REGION=ap-northeast-1
      - BEDROCK_REGION=us-west-2
      - BEDROCK_MODEL_ID=anthropic.claude-3-5-sonnet-20241022-v2:0
      - SNS_TOPIC_ARN=none
      - METRICS_NAME_1=ALB_REQUEST_COUNT
      - METRICS_NAME_2=ECS_CPU_UTILIZED
